### ISSUE TITLE
Gene Individual page

### ISSUE THREAD

**Issue by parinaznasr** [bhklab/PharmacoDB-JS#390]
- [x] bar plot is not correct 
- [x] Durgs summary - rename
- [x] Drug summary : add annotated targets column - table is wrong , #382
- [x] Drug summary: fix the title "Compounds tested targetting A2M-AS1" #382
- [x] Drug summary : #382
- [x] Add plot or descriptions to the first section
- [x]  Top Drugs : Not showing drugs like lapatinib; only shows (-)-Epigallocatechin gallate
- [x]  Top Drugs : rename content in column "Feature Type"
 check : Screen Shot 2021-09-16 at 12 59 24 PM
- [x] Top Drugs : change "Stat" to "Sensitivity Metric"
- [x] Top Drugs : sort column by "Correlation" and assign colors for- and + values
- [x] Top Drugs : remove column "Significant by Permutation Test" for now.
- [x] #84

**Comment by sisiranair** [comment]
- [ ] Top Drugs : Not showing drugs like lapatinib; only shows (-)-Epigallocatechin gallate
- [ ] Top Drugs : rename content in column "Feature Type"
![Screen Shot 2021-09-16 at 12 59 24 PM](https://user-images.githubusercontent.com/41380598/133703633-9625bd69-50b3-414b-ba61-f30465780791.png)
- [ ] Top Drugs : change "Stat" to "Sensitivity metric"
- [ ]  Top Drugs : sort column by "Correlation" and assign colors for- and + values
- [ ] Top Drugs : remove column "Significant by Permutation Test" for now.
- [ ] Plots : GRAY dataset had 0 compounds tested (not 100% clear what this issue is)
