### ISSUE TITLE
Cell line pages not loading

### ISSUE THREAD

**Issue by sisiranair** [bhklab/PharmacoDB-JS#403]
https://pharmacodb.ca/cell_lines/MCF-7/E610892021_
https://pharmacodb.ca/cell_lines/LY2_874_2019

**Comment by mnakano** [comment]
I could reproduce the first case, and turns out this is because the cell line uid include a slash character which is seen as a URL divider in the react library we use to route users to another page, so the full uid was not sent to the backend, and thus the data in not loaded. Since the cause is clear in this case, I could implement a fix.

The second link worked fine with my laptop, opened with both chrome and safari. I cannot pinpoint anything in the application implementation or the specific cell line data that's causing the issue, so we will mark the second link issue-free for now.
